//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Plan struct {
	PlanID      string `sql:"primary_key" db:"plan_id"`
	DisplayName string `db:"display_name"`
}
