//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/cloudy-clip/api/internal/user/model"
	"time"
)

type VerificationCode struct {
	VerificationCodeID string                 `sql:"primary_key" db:"verification_code_id"`
	VerificationType   model.VerificationType `db:"verification_type"`
	CreatedAt          time.Time              `db:"created_at"`
	UserID             string                 `db:"user_id"`
}
