//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/cloudy-clip/api/internal/billing/model"
	"time"
)

type Payment struct {
	PaymentID       string              `sql:"primary_key" db:"payment_id"`
	ChargeID        *string             `db:"charge_id"` // Stripe's charge ID, null for refunds
	Subtotal        string              `db:"subtotal"`
	Discount        string              `db:"discount"`
	Tax             string              `db:"tax"`
	AmountDue       string              `db:"amount_due"`
	CurrencyCode    string              `db:"currency_code"`
	PaidAt          time.Time           `db:"paid_at"`
	Status          model.PaymentStatus `db:"status"`
	FailureReason   *string             `db:"failure_reason"`
	PaymentReason   model.PaymentReason `db:"payment_reason"`
	UserID          string              `db:"user_id"`
	PaymentMethodID *string             `db:"payment_method_id"`
}
