//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/cloudy-clip/api/internal/task/model"
	"time"
)

type Task struct {
	TaskID    string           `sql:"primary_key" db:"task_id"`
	Type      model.TaskType   `db:"type"`
	Status    model.TaskStatus `db:"status"`
	UserID    string           `db:"user_id"`
	UpdatedAt time.Time        `db:"updated_at"`
	Comment   *string          `db:"comment"`
}
