//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PlanEntitlement struct {
	PlanEntitlementID string `sql:"primary_key" db:"plan_entitlement_id"`
	Type              string `db:"type"`
	Quantity          int16  `db:"quantity"`
	Restricted        bool   `db:"restricted"`
	PlanID            string `db:"plan_id"`
}
