//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PaymentMethod struct {
	PaymentMethodID string `sql:"primary_key" db:"payment_method_id"` // Will be stripe's payment method ID
	ExpMonth        string `db:"exp_month"`
	ExpYear         string `db:"exp_year"`
	Last4           string `db:"last4"`
	Brand           string `db:"brand"`
	IsDefault       bool   `db:"is_default"`
	IsDeleted       bool   `db:"is_deleted"`
	UserID          string `db:"user_id"`
}
