//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/cloudy-clip/api/internal/subscription/model"
	"time"
)

type Subscription struct {
	UserID             string                                `sql:"primary_key" db:"user_id"`
	PlanOfferingID     string                                `db:"plan_offering_id"`
	CanceledAt         *time.Time                            `db:"canceled_at"`
	CancellationReason *model.SubscriptionCancellationReason `db:"cancellation_reason"`
}
