//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/cloudy-clip/api/internal/user/model"
	"time"
)

type User struct {
	UserID         string                 `sql:"primary_key" db:"user_id"`
	Email          string                 `db:"email"`
	Password       string                 `db:"password"`
	Salt           string                 `db:"salt"`
	DisplayName    string                 `db:"display_name"`
	Status         model.UserStatus       `db:"status"`
	StatusReason   model.UserStatusReason `db:"status_reason"`
	Provider       model.Oauth2Provider   `db:"provider"`
	LastLoggedInAt time.Time              `db:"last_logged_in_at"`
	CreatedAt      time.Time              `db:"created_at"`
	UpdatedAt      time.Time              `db:"updated_at"`
}
