//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type BillingInfo struct {
	UserID               string  `sql:"primary_key" db:"user_id"`
	BillingCustomerID    *string `db:"billing_customer_id"`
	StripeSubscriptionID *string `db:"stripe_subscription_id"`
	CountryCode          *string `db:"country_code"`
	PostalCode           *string `db:"postal_code"`
}
