//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PlanOffering struct {
	PlanOfferingID  string `sql:"primary_key" db:"plan_offering_id"`
	Price           string `db:"price"`
	DiscountedPrice string `db:"discounted_price"`
	RenewedIn       string `db:"renewed_in"`
	PlanID          string `db:"plan_id"`
}
