export type PaymentReason =
  | 'UNKNOWN'
  | 'SUBSCRIPTION_CANCELLATION'
  | 'SUBSCRIPTION_DOWNGRADE'
  | 'NEW_SUBSCRIPTION'
  | 'SUBSCRIPTION_REACTIVATION'
  | 'SUBSCRIPTION_RENEWAL'
  | 'SUBSCRIPTION_UPGRADE';
