//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	BillingInfoTable = BillingInfoTable.FromSchema(schema)
	PaymentTable = PaymentTable.FromSchema(schema)
	PaymentMethodTable = PaymentMethodTable.FromSchema(schema)
	PlanTable = PlanTable.FromSchema(schema)
	PlanEntitlementTable = PlanEntitlementTable.FromSchema(schema)
	PlanOfferingTable = PlanOfferingTable.FromSchema(schema)
	SubscriptionTable = SubscriptionTable.FromSchema(schema)
	TaskTable = TaskTable.FromSchema(schema)
	TaxRateTable = TaxRateTable.FromSchema(schema)
	UserTable = UserTable.FromSchema(schema)
	VerificationCodeTable = VerificationCodeTable.FromSchema(schema)
}
